"""Contamination filter — filters out bot-generated turns from calibration data.

Simple heuristic: exclude turns where the response was generated by the bot
(not written/approved by the creator).
"""

from typing import Dict, List, Tuple


def filter_turns(
    conversations: List[Dict],
    all_turns: List[Dict],
) -> Tuple[List[Dict], List[Dict], Dict]:
    """Filter contaminated turns from conversation pairs.

    Since load_conversation_pairs already filters on status='sent' and
    approved_by in ('', 'creator', 'creator_manual'), most contamination
    is already excluded. This pass-through returns all turns as clean.

    Returns:
        (clean_turns, excluded_turns, filter_stats)
    """
    return all_turns, [], {"contaminated_conversations": 0}
