export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>

      <div className="prose prose-invert max-w-none space-y-8">
        <p className="text-gray-300">
          Last updated: December 2024
        </p>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">1. Service Description</h2>
          <p className="text-gray-300">
            Clonnect ("the Service") is an AI-powered platform that helps content creators automate
            their direct message responses across Instagram, Telegram, and WhatsApp. The Service
            uses artificial intelligence to generate responses that mimic the creator's communication style.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">2. Acceptance of Terms</h2>
          <p className="text-gray-300">
            By using Clonnect, you agree to these Terms of Service. If you do not agree,
            please do not use the Service. We reserve the right to modify these terms at any time,
            and continued use of the Service constitutes acceptance of any changes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">3. User Responsibilities</h2>
          <ul className="list-disc list-inside text-gray-300 space-y-2">
            <li>You must provide accurate information when creating your account</li>
            <li>You are responsible for the content your AI clone generates and sends</li>
            <li>You must comply with the terms of service of connected platforms (Instagram, Telegram, WhatsApp)</li>
            <li>You must not use the Service for spam, harassment, or illegal activities</li>
            <li>You must inform recipients that they may be communicating with an AI when required by law</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">4. Acceptable Use</h2>
          <p className="text-gray-300">
            The Service may only be used for legitimate business communication. Prohibited uses include:
          </p>
          <ul className="list-disc list-inside text-gray-300 space-y-2 mt-2">
            <li>Sending unsolicited commercial messages (spam)</li>
            <li>Impersonating others without their consent</li>
            <li>Distributing malware or phishing content</li>
            <li>Violating applicable laws or regulations</li>
            <li>Infringing on intellectual property rights</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">5. Intellectual Property</h2>
          <p className="text-gray-300">
            The Clonnect platform, including its design, code, and AI models, is owned by Clonnect.
            You retain ownership of your content, including your personality configuration, products,
            and conversation data. By using the Service, you grant us a license to process your
            content for the purpose of providing the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">6. AI-Generated Content</h2>
          <p className="text-gray-300">
            Responses generated by your AI clone are automated and may not always be accurate.
            You are responsible for monitoring and reviewing the responses your clone sends.
            Clonnect is not liable for any damages resulting from AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">7. Limitation of Liability</h2>
          <p className="text-gray-300">
            Clonnect is provided "as is" without warranties of any kind. We are not responsible for:
          </p>
          <ul className="list-disc list-inside text-gray-300 space-y-2 mt-2">
            <li>Inaccurate AI-generated responses</li>
            <li>Missed messages or delivery failures</li>
            <li>Platform API changes that affect functionality</li>
            <li>Loss of business or revenue</li>
            <li>Data loss beyond our reasonable control</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">8. Data and Privacy</h2>
          <p className="text-gray-300">
            Your privacy is important to us. Please review our{" "}
            <a href="/privacy" className="text-cyan-400 hover:underline">Privacy Policy</a>{" "}
            for information on how we collect, use, and protect your data.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">9. Termination</h2>
          <p className="text-gray-300">
            We may terminate or suspend your access to the Service at any time for violation of
            these terms. You may also terminate your account at any time by contacting support.
            Upon termination, your data will be deleted according to our data retention policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">10. Governing Law</h2>
          <p className="text-gray-300">
            These terms are governed by the laws of Spain. Any disputes shall be resolved
            in the courts of Barcelona, Spain.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-4">11. Contact</h2>
          <p className="text-gray-300">
            For questions about these terms, contact us at{" "}
            <a href="mailto:legal@clonnect.com" className="text-cyan-400 hover:underline">
              legal@clonnect.com
            </a>
          </p>
        </section>
      </div>

      <div className="mt-12 flex gap-4 text-sm text-gray-500">
        <a href="/privacy" className="hover:text-gray-300 transition-colors">Privacy Policy</a>
        <span>•</span>
        <a href="/docs" className="hover:text-gray-300 transition-colors">Help & FAQ</a>
      </div>
    </div>
  );
}
