"""
Contamination Filter v3 - Deep pattern + statistical detection.

Detects bot-contaminated turns in real conversation data.
3 layers:
  Layer 1: Known bot indicators (fixed patterns from previous bots)
  Layer 2: Subtle bot patterns (formal language Stefano never uses)
  Layer 3: Statistical conversation-level detection (avg length anomalies)

Used by:
  - creator_calibration_pipeline.py (clean training data)
  - evaluator.py (exclude contaminated turns from scoring)
"""

import re
from typing import Dict, List, Set, Tuple


# ─── Layer 1: Known bot indicators (obvious) ─────────────────────────────────

BOT_INDICATORS = [
    # ChatGPT / generic bot signatures
    "como asistente virtual",
    "como modelo de lenguaje",
    "como inteligencia artificial",
    "no tengo la capacidad de",
    "lamento no poder",
    "como IA",
    "como ia,",
    "soy un bot",
    "soy una inteligencia artificial",
    "no puedo proporcionar",
    "no estoy en posición de",
    # Previous bot (soymariaeuget / lucuranatural style)
    "¡eso suena genial!",
    "¡qué emocionante!",
    "¡qué interesante!",
    "¡qué maravilla!",
    "¡qué bonito!",
    "me encantaría saber más sobre",
    "cuéntame más sobre",
    "me parece una idea fantástica",
    "suena como una experiencia increíble",
    "¡qué buena elección!",
    "¡me alegra mucho saber eso!",
    "recuerda que siempre",
    "es maravilloso que",
    "te felicito por",
    "eso demuestra tu",
    # Formal bot closers
    "si necesitas algo más, no dudes",
    "estoy aquí para ayudarte en lo que necesites",
    "no dudes en contactarme",
    "espero haberte ayudado",
    "¿hay algo más en lo que pueda ayudarte",
    "¿en qué más puedo ayudarte",
    "si tienes más preguntas",
]

# ─── Layer 2: Subtle bot patterns (v3) ───────────────────────────────────────

SUBTLE_BOT_PATTERNS = [
    "oportunidades interesantes",
    "siempre es bueno compartir",
    "¿hay algo más que te gustaría",
    "es una gran idea",
    "si quieres compartir algo más",
    "¿tienes algún lugar en mente",
    "aquí estoy para ayudarte",
    "no dudes en preguntar",
    "estoy aquí para lo que necesites",
    "es importante que sepas",
    "definitivamente",
    "fundamentalmente",
    "abarca varios aspectos",
    # Additional subtle patterns from analysis
    "es comprensible que",
    "es totalmente normal",
    "¡qué gran pregunta!",
    "puedo entender cómo te sientes",
    "eso es algo muy válido",
    "me encanta que compartas",
    "es genial que estés",
    "suena como una gran oportunidad",
    "es una excelente opción",
    "como primer paso",
]

# ─── Layer 3: Structural patterns ────────────────────────────────────────────

# Regex patterns that detect bot-like structure
BOT_STRUCTURAL_PATTERNS = [
    # Numbered lists (Stefano never does this)
    r"^\d+[\.\)]\s+\w",
    # Bullet points
    r"^[-•]\s+\w",
    # Multiple exclamation-emoji combos (bot signature: "¡Genial! 😊 ¡Me encanta!")
    r"¡[^!]{3,20}!\s*[😊🎉✨💪🌟🙌❤️💕🎊👏]",
    # Overly formal question structure
    r"¿(?:hay algo|te gustaría|necesitas|puedo ayudarte|en qué)",
]


def is_bot_response(response: str) -> Tuple[bool, str]:
    """
    Check if a response was likely generated by a bot.

    Returns:
        (is_contaminated, reason)
    """
    if not response:
        return False, ""

    resp_lower = response.lower().strip()

    # Layer 1: Known bot indicators
    for indicator in BOT_INDICATORS:
        if indicator in resp_lower:
            return True, f"bot_indicator: {indicator[:40]}"

    # Layer 2: Subtle patterns
    for pattern in SUBTLE_BOT_PATTERNS:
        if pattern in resp_lower:
            return True, f"subtle_pattern: {pattern[:40]}"

    # Layer 3: Structural patterns
    for line in response.split("\n"):
        for pattern in BOT_STRUCTURAL_PATTERNS:
            if re.search(pattern, line.strip()):
                return True, f"structural: {pattern[:40]}"

    # Layer 3b: Multiple sentences with exclamation + emoji (bot loves this)
    excl_emoji_count = len(re.findall(
        r"!\s*[😊🎉✨💪🌟🙌❤️💕🎊👏😃🥳🤩]", response
    ))
    if excl_emoji_count >= 3:
        return True, "excessive_excl_emoji"

    return False, ""


def detect_contaminated_conversations(
    conversations: List[Dict],
    creator_median_length: int = 19,
) -> Set[str]:
    """
    Statistical detection of contaminated conversations.

    A conversation is flagged if:
    1. Average response length > 5x creator median (bot writes way more)
    2. >40% of turns have responses >100 chars AND conversation has >=5 turns

    Args:
        conversations: List of conversation dicts with 'turns' and 'lead_username'
        creator_median_length: Median response length of the real creator

    Returns:
        Set of contaminated lead_username values
    """
    contaminated: Set[str] = set()

    for conv in conversations:
        turns = conv.get("turns", [])
        if len(turns) < 3:
            continue

        username = conv.get("lead_username", "")
        if not username:
            continue

        lengths = [t.get("real_length", len(t.get("real_response", ""))) for t in turns]
        if not lengths:
            continue

        avg_len = sum(lengths) / len(lengths)

        # Rule 1: Average way too long
        if avg_len > creator_median_length * 5:
            contaminated.add(username)
            continue

        # Rule 2: High percentage of long responses
        long_pct = sum(1 for length in lengths if length > 100) / len(lengths)
        if long_pct > 0.40 and len(turns) >= 5:
            contaminated.add(username)

    return contaminated


def filter_turns(
    conversations: List[Dict],
    all_turns: List[Dict],
    creator_median_length: int = 19,
) -> Tuple[List[Dict], List[Dict], Dict]:
    """
    Filter contaminated turns from a list of turns.

    Applies all 3 layers:
    1. Individual turn pattern matching
    2. Conversation-level statistical detection
    3. Returns clean turns, excluded turns, and stats

    Args:
        conversations: Full conversation data (for statistical detection)
        all_turns: All turns to filter
        creator_median_length: Creator's median response length

    Returns:
        (clean_turns, excluded_turns, stats_dict)
    """
    # Step 1: Detect contaminated conversations (statistical)
    contaminated_convs = detect_contaminated_conversations(
        conversations, creator_median_length
    )

    # Step 2: Filter individual turns
    clean_turns = []
    excluded_turns = []
    reasons = {
        "bot_indicator": 0,
        "subtle_pattern": 0,
        "structural": 0,
        "excessive_excl_emoji": 0,
        "contaminated_conversation": 0,
    }

    for turn in all_turns:
        username = turn.get("lead_username", "")
        response = turn.get("real_response", "")

        # Check conversation-level contamination
        if username in contaminated_convs:
            # Allow short responses from contaminated convs (might be real)
            real_len = turn.get("real_length", len(response))
            if real_len > 80:
                turn["exclusion_reason"] = "contaminated_conversation"
                excluded_turns.append(turn)
                reasons["contaminated_conversation"] += 1
                continue

        # Check individual turn
        is_bot, reason = is_bot_response(response)
        if is_bot:
            reason_key = reason.split(":")[0] if ":" in reason else reason
            turn["exclusion_reason"] = reason
            excluded_turns.append(turn)
            reasons[reason_key] = reasons.get(reason_key, 0) + 1
            continue

        clean_turns.append(turn)

    stats = {
        "total_turns": len(all_turns),
        "clean_turns": len(clean_turns),
        "excluded_turns": len(excluded_turns),
        "contaminated_conversations": sorted(contaminated_convs),
        "exclusion_reasons": reasons,
        "exclusion_pct": round(100 * len(excluded_turns) / max(len(all_turns), 1), 1),
    }

    return clean_turns, excluded_turns, stats
